services:
  laravel:
    build:
      context: ./
    ports:
      - "8000:80"
    working_dir: /var/www/html
    networks:
      - laravel_network

  react:
    build:
      context: ../React-App_DWEC--LARAVEL/
    ports:
      - "80:80"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge