services:
  app:
    build:
      context: ./
    ports:
      - "${HTTPD_PORT}:80"
    working_dir: /var/www/html
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge